#!/usr/bin/env python3

import sys, subprocess



def main() -> int: # {
    process = subprocess.Popen(['pacman', '-S', 'python-nobash'])
    process.wait()

    if process.returncode == 0:
        print('\nSuccess!')

    return process.returncode
# }

if __name__ == '__main__':
    sys.exit(main())


